import os
import sys
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Optional
from contextlib import asynccontextmanager
import uvicorn
import uuid
from pydantic import BaseModel
from logger import get_user_cases, get_case_messages, delete_case
from engine import QueryEngine

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# 1. Lifespan Manager: Use app.state for future-proof state management
@asynccontextmanager
async def lifespan(app: FastAPI):
    print("⏳ Starting Law-GPT API Server Worker...")
    try:
        # Store engine in app state instead of a global variable
        app.state.engine = QueryEngine()
        print("✅ API Engine successfully loaded into VRAM.")
    except Exception as e:
        print(f"❌ Failed to load Engine: {e}")
        app.state.engine = None

    yield

    print("🛑 Shutting down Law-GPT API...")
    app.state.engine = None

app = FastAPI(
    title="Law-GPT API",
    description="Enterprise REST API for Indian Legal AI Inference",
    version="1.0.0",
    lifespan=lifespan
)

# 2. Add CORS Middleware so Next.js can communicate with FastAPI
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, replace "*" with your actual frontend URL (e.g. "http://localhost:3000")
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class LegalQuery(BaseModel):
    query: str
    user_id: Optional[str] = "anonymous"
    case_id: Optional[str] = None
    title: Optional[str] = "New Legal Case"

class LegalResponse(BaseModel):
    answer: str
    sources: List[str]
    confidence: float
    status: str
    inference_time_seconds: float
    case_id: str

# 3. Removed 'async' from this endpoint so FastAPI runs the heavy LLM task in a threadpool!
@app.post("/api/v1/consult", response_model=LegalResponse)
def consult_lawyer(request: LegalQuery, req: Request):
    engine = req.app.state.engine

    if engine is None:
        raise HTTPException(status_code=500, detail="AI Engine is offline or still loading.")

    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")

    active_case_id = request.case_id or str(uuid.uuid4())

    try:
        result = engine.ask(
            query_text=request.query,
            user_id=request.user_id,
            case_id=active_case_id,
            title=request.title
        )

        return LegalResponse(
            answer=result.get("answer", "Error generating response."),
            sources=result.get("sources", []),
            confidence=result.get("confidence", 0.0),
            status=result.get("status", "Unknown"),
            inference_time_seconds=result.get("time", 0.0),
            case_id=active_case_id
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

from pydantic import BaseModel

class DraftRequest(BaseModel):
    docType: str
    clientName: str
    recipientName: str
    shortSubject: str
    dateOfIncident: str
    grievance: str

@app.post("/api/v1/draft")
async def generate_draft(data: DraftRequest):
    # This is the prompt that tells Llama exactly how to behave as a lawyer
    prompt = f"""
    You are a senior Indian Advocate. Draft a formal {data.docType.replace('_', ' ')}.

    FACTS:
    - Client: {data.clientName}
    - Opponent: {data.recipientName}
    - Subject: {data.shortSubject}
    - Date: {data.dateOfIncident}
    - Details: {data.grievance}

    STRICT RULES:
    1. Use formal Indian legal terminology.
    2. Format it as a professional Legal Notice.
    3. Include a 15-day notice period for rectification.
    4. Do not invent facts outside of what is provided.
    5. End with 'Advocate for {data.clientName}'.
    """

    # Call your Llama model here (similar to your chat endpoint)
    # response = llm.generate(prompt)
    # return {"draft": response}

    # For now, we'll return a success message so you can test the connection
    return {"draft": f"DRAFT GENERATED BY LLAMA-3.1:\n\nRegarding: {data.shortSubject}\n..."}

@app.get("/api/v1/cases/{user_id}")
async def get_sidebar_cases(user_id: str):
    cases = get_user_cases(user_id)
    return {"cases": cases}

@app.get("/api/v1/case/{case_id}")
async def get_chat_history(case_id: str):
    """Endpoint for the frontend to load a specific chat's message history."""
    messages = get_case_messages(case_id)
    return {"messages": messages}

@app.delete("/api/v1/case/{case_id}")
async def delete_chat_case(case_id: str):
    """Endpoint to delete a specific chat history."""
    success = delete_case(case_id)
    if success:
        return {"status": "success", "message": "Case deleted"}
    else:
        raise HTTPException(status_code=500, detail="Failed to delete case")

@app.get("/health")
async def health_check():
    return {"status": "online", "model": "Llama-3.1-8B-Instruct", "gpu_acceleration": True}

if __name__ == "__main__":
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=False)
